name = "SpinLatticePhaseChanges"
uuid = "46814090-1040-4a89-9c85-9321c9130b5a"
authors = ["benbutterworth <127899580+benbutterworth@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
